module

public import CebotarevDensity.Abelian

/-!
# Chebotarev's density theorem

For a finite Galois extension `L/K` of number fields with Galois group
`G = Gal(L/K)` and a conjugacy class `C` of `G`, the Dirichlet density of
primes `𝔭` of `𝓞 K` (unramified in `L`) whose Frobenius conjugacy class is
`C` equals `|C| / |G|`.

The proof (Sharifi 7.2.2 Step 1; Stevenhagen–Lenstra Appendix paragraph 2)
reduces the conjugacy-class statement to the cyclic case via the
intermediate field `E = L^⟨σ⟩` for `σ ∈ C`:

- `L/E` is cyclic of degree `f = |⟨σ⟩|`, hence abelian, so the abelian case
  (`chebotarev_abelian`) gives density `1/f` for primes of `E` with
  Frobenius `σ`.
- A counting argument over the primes of `L` lying above a prime of `K`
  shows that, for the set `S` of primes `𝔭` of `K` whose Frobenius class is
  `C`, and `T_σ` the set of primes `P` of `E` with `σ_P = σ`,

      δ_K(S) = (f · |C| / |G|) · δ_E(T_σ).

  With `δ_E(T_σ) = 1/f` from the cyclic case, this gives `δ_K(S) = |C|/|G|`.

## Main results

* `Chebotarev.chebotarev_density` — Chebotarev's density
  theorem in conjugacy-class form.
* `Chebotarev.dirichlet_primes_in_AP` — Dirichlet's theorem
  on primes in arithmetic progressions, as a corollary.
* `Chebotarev.density_split_completely` — the density of
  primes of `K` that split completely in `L` is `1/[L:K]`.

## References

* Sharifi, *Algebraic Number Theory*, Theorem 7.2.2 (`docs/algnum.pdf`,
  pp. 142–144).
* Stevenhagen–Lenstra, *Chebotarëv and his density theorem*, Appendix
  (`docs/cheb.pdf`, p. 18).
-/

@[expose] public section

noncomputable section

open NumberField

namespace Chebotarev

variable (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L]
  [Algebra K L] [IsGalois K L]

/-! ### Sub-lemmas for `chebotarev_density`

Decomposed per Sharifi 7.2.2 Step 1 (p. 143). Source quote (verbatim):

> "Let σ ∈ C and E = L^⟨σ⟩ so that L/E is cyclic of degree f = |⟨σ⟩|.
> […] Let T_σ be the set of primes P of E unramified in L and over K
> with Frobenius φ_P at a prime of L over P equal to σ. If P ∈ T_σ,
> then φ_P = σ fixes E, so P has degree one over K. As P is by
> definition inert in L, there are exactly |G|/f primes of L over
> P ∩ K. As the Frobenius elements of such primes are distributed
> evenly among the elements of the conjugacy class C of σ, exactly
> |G|/f|C| of these have Frobenius σ. We may then compute the
> Dirichlet density of S: δ(S) = lim_{s→1+} Σ_𝔭∈S N𝔭^{-s} / Σ_𝔭
> N𝔭^{-s} = (f|C|/|G|) lim_{s→1+} Σ_P∈T_σ NP^{-s} / Σ_P NP^{-s} =
> (f|C|/|G|) δ(T_σ), recalling once again that Σ_𝔭 N𝔭^{-s} ~ Σ_P
> NP^{-s}. Supposing the theorem for K/E, we have δ(T_σ) = 1/f, and
> we therefore obtain δ(S) = |C|/|G|."

Four sub-lemmas:
(i) Cyclic subextension: `E = L^⟨σ⟩`, `[L:E] = |⟨σ⟩| = ord(σ)`.
(ii) Above-counting: for `𝔭 ∈ S`, exactly `|G|/(f|C|)` primes `𝔓` of
    `𝓞 L` over `𝔭` have `Frob_𝔓 = σ`, each "below" a unique `P ∈ T_σ`.
(iii) Density relation `δ_K(S) = (f|C|/|G|) · δ_E(T_σ)` (uses
    `Σ N𝔭^{-s} ~ Σ NP^{-s}` from Density.lean).
(iv) Apply `chebotarev_abelian` to `L/E` (cyclic): `δ_E(T_σ) = 1/f`.
-/

/-- **API gap — order of the Frobenius equals the residue degree.** For an unramified
prime `𝔓` of `𝓞 L`, the decomposition group `D_𝔓` is cyclic of order the residue degree
`f = [κ(𝔓) : κ(𝔭)]`, generated by `Frob_𝔓`; hence `orderOf Frob_𝔓 = f`. mathlib has
`Ideal.card_stabilizer_eq_card_inertia_mul_finrank` (`|D_𝔓| = |I_𝔓| · f`) but not that
`Frob_𝔓` generates `D_𝔓`, so this leaf is a genuine API gap. -/
theorem orderOf_frobeniusAt_eq_finrank
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (𝔓 : Ideal (𝓞 L)) [𝔓.IsPrime]
    (h : Ideal.ramificationIdx (𝔓.under (𝓞 K)) 𝔓 = 1) :
    orderOf (frobeniusAt K L 𝔓 h) = Module.finrank (𝓞 K ⧸ 𝔓.under (𝓞 K)) (𝓞 L ⧸ 𝔓) := by
  sorry

/-- **Orbit–stabilizer count via the residue degree** (Sharifi 7.2.2 Step 1, p. 143).
The number of primes of `𝓞 L` above `𝔭` times the residue degree `[κ(𝔓₀) : κ(𝔭)]` of any
prime `𝔓₀` above `𝔭` equals `|Gal(L/K)|`. Discharged by mathlib's
`Ideal.ncard_primesOver_mul_card_inertia_mul_finrank` (orbit–stabilizer) with trivial
inertia (`Ideal.card_inertia_eq_ramificationIdxIn` + `UnramifiedIn` ⟹ `e = 1`), after
identifying `{𝔓 // 𝔓.IsPrime ∧ 𝔓.LiesOver 𝔭 ∧ 𝔓 ≠ ⊥}` with `𝔭.primesOver (𝓞 L)`. -/
theorem card_primesAbove_mul_finrank_eq
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭)
    (𝔓₀ : Ideal (𝓞 L)) [𝔓₀.IsPrime] (hlo : 𝔓₀.LiesOver 𝔭) :
    Nat.card {𝔓 : Ideal (𝓞 L) // 𝔓.IsPrime ∧ 𝔓.LiesOver 𝔭 ∧ 𝔓 ≠ ⊥}
        * Module.finrank (𝓞 K ⧸ 𝔓₀.under (𝓞 K)) (𝓞 L ⧸ 𝔓₀) = Nat.card Gal(L/K) := by
  sorry

/-- The residue degree `[κ(𝔓) : κ(𝔭)]` at an unramified prime `𝔓` above `𝔭`, whose
Frobenius class is `C = [σ]`, equals `orderOf σ`: `Frob_𝔓` generates `D_𝔓` of order `f`
(`orderOf_frobeniusAt_eq_finrank`) and is conjugate to `σ`
(`frobeniusClass_eq_mk_frobeniusAt`), so the orders agree. -/
theorem finrank_residue_eq_orderOf
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (σ : Gal(L/K)) (C : ConjClasses Gal(L/K)) (hσ : ConjClasses.mk σ = C)
    (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭) (hCfrob : frobeniusClass K L 𝔭 = C)
    (𝔓 : Ideal (𝓞 L)) [𝔓.IsPrime] (hlo : 𝔓.LiesOver 𝔭) :
    Module.finrank (𝓞 K ⧸ 𝔓.under (𝓞 K)) (𝓞 L ⧸ 𝔓) = orderOf σ := by
  have hconj : IsConj
      (frobeniusAt K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hlo)) σ := by
    rw [← ConjClasses.mk_eq_mk_iff_isConj,
      ← frobeniusClass_eq_mk_frobeniusAt K L 𝔭 hunr 𝔓 hlo, hCfrob, hσ]
  obtain ⟨c, hc⟩ := isConj_iff.mp hconj
  rw [← hc, ← MulAut.conj_apply, MulEquiv.orderOf_eq,
    orderOf_frobeniusAt_eq_finrank K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hlo)]

/-- **Orbit–stabilizer for the primes above `𝔭`** (Sharifi 7.2.2 Step 1, p. 143). The
Galois group acts transitively on the primes of `𝓞 L` above `𝔭`, with stabiliser the
decomposition group `D_𝔓`; for an unramified prime `D_𝔓` is cyclic of order `f = ord σ`
(generated by the Frobenius). Hence the number of primes above `𝔭` times `ord σ` is
`|Gal(L/K)|`. -/
theorem card_primesAbove_mul_orderOf_eq
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (σ : Gal(L/K)) (C : ConjClasses Gal(L/K)) (_hσ : ConjClasses.mk σ = C)
    (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭)
    (_hCfrob : frobeniusClass K L 𝔭 = C) :
    Nat.card {𝔓 : Ideal (𝓞 L) // 𝔓.IsPrime ∧ 𝔓.LiesOver 𝔭 ∧ 𝔓 ≠ ⊥} * orderOf σ
      = Nat.card Gal(L/K) := by
  obtain ⟨𝔓₀, hp₀, hlo₀, _⟩ := exists_prime_liesOver K L 𝔭 (UnramifiedIn.ne_bot K L hunr)
  haveI := hp₀
  rw [← finrank_residue_eq_orderOf K L σ C _hσ 𝔭 hunr _hCfrob 𝔓₀ hlo₀]
  exact card_primesAbove_mul_finrank_eq K L 𝔭 hunr 𝔓₀ hlo₀

/-- **Equipotent Frobenius fibres** (the "distributed evenly" of Sharifi 7.2.2, p. 143).
For `IsConj σ σ'`, conjugating by the witnessing element is a bijection between the primes
above `𝔭` with `Frob_𝔓 = σ` and those with `Frob_𝔓 = σ'` (via `frobeniusAt_conj_eq`), so the
two Frobenius fibres have equal cardinality. -/
theorem frobeniusFibre_card_eq_of_isConj
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭)
    (σ σ' : Gal(L/K)) (hc : IsConj σ σ') :
    Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭) (_ : 𝔓 ≠ ⊥),
        frobeniusAt K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hP) = σ}
      = Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭) (_ : 𝔓 ≠ ⊥),
        frobeniusAt K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hP) = σ'} := by
  sorry

/-- **Balanced fibre count.** If every prime above `𝔭` has Frobenius in the class `C = [σ]`
and conjugate Frobenius values occur equally often (`hequi`), the total number of primes
above `𝔭` is `|C|` times the number with `Frob_𝔓 = σ`: partition by the (class-`C`-valued)
Frobenius via `Finset.card_eq_sum_card_fiberwise`, then `Finset.sum_const` using `hequi`. -/
theorem card_primesAbove_eq_card_carrier_mul_frobeniusFibre
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (σ : Gal(L/K)) (C : ConjClasses Gal(L/K)) (hσ : ConjClasses.mk σ = C)
    (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭) (hCfrob : frobeniusClass K L 𝔭 = C)
    (hequi : ∀ σ' : Gal(L/K), IsConj σ σ' →
      Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭) (_ : 𝔓 ≠ ⊥),
          frobeniusAt K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hP) = σ}
        = Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭) (_ : 𝔓 ≠ ⊥),
          frobeniusAt K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hP) = σ'}) :
    Nat.card {𝔓 : Ideal (𝓞 L) // 𝔓.IsPrime ∧ 𝔓.LiesOver 𝔭 ∧ 𝔓 ≠ ⊥}
      = Nat.card C.carrier
        * Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭) (_ : 𝔓 ≠ ⊥),
          frobeniusAt K L 𝔓 (UnramifiedIn.ramificationIdx_eq_one K L hunr 𝔓 hP) = σ} := by
  sorry

/-- **Even distribution of Frobenius over the conjugacy class** (Sharifi 7.2.2 Step 1,
p. 143). The Frobenius elements of the primes above `𝔭` sweep out the conjugacy class
`C = [σ]` evenly, so the number of primes above `𝔭` with `Frob_𝔓 = σ` times `|C|` equals
the total number of primes above `𝔭`. -/
theorem count_frobenius_eq_sigma_mul_card_carrier
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (σ : Gal(L/K)) (C : ConjClasses Gal(L/K)) (_hσ : ConjClasses.mk σ = C)
    (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭)
    (_hCfrob : frobeniusClass K L 𝔭 = C) :
    Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭)
        (_ : 𝔓 ≠ ⊥),
        frobeniusAt K L 𝔓
            (by rw [show 𝔓.under (𝓞 K) = 𝔭 from hP.over.symm]; exact hunr 𝔓 hP)
          = σ}
      * Nat.card C.carrier
      = Nat.card {𝔓 : Ideal (𝓞 L) // 𝔓.IsPrime ∧ 𝔓.LiesOver 𝔭 ∧ 𝔓 ≠ ⊥} := by
  rw [mul_comm]
  exact (card_primesAbove_eq_card_carrier_mul_frobeniusFibre K L σ C _hσ 𝔭 hunr _hCfrob
    fun σ' hc => frobeniusFibre_card_eq_of_isConj K L 𝔭 hunr σ σ' hc).symm

/-- Sharifi 7.2.2 Step 1, above-counting (p. 143). Verbatim source quote:
"exactly `|G|/f|C|` of these have Frobenius σ". For a prime `𝔭` of
`𝓞 K` with Frobenius class `C` and a representative `σ ∈ C`, the count
of primes `𝔓` of `𝓞 L` above `𝔭` with `Frob_𝔓 = σ` is `|G|/(f·|C|)`.

This is the substantive new sub-lemma for the conjugacy-class →
cyclic reduction; the fixed-field cyclic-subextension setup
(`E = L^⟨σ⟩`, `[L:E] = ord σ`) is mathlib's `IntermediateField.fixedField`
and `IsGalois.card_aut_eq_finrank` applied at `⟨σ⟩`, and the density-lift
formula `δ_K(S) = (f|C|/|G|) δ_E(T_σ)` follows from this counting
together with `Σ N𝔭^{-s} ~ Σ NP^{-s}` (Sharifi 7.1.12 applied to both
`K` and `E`). -/
theorem count_primes_above_with_frobenius_eq_sigma
    (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L] [IsGalois K L]
    [FiniteDimensional K L] (σ : Gal(L/K)) (C : ConjClasses Gal(L/K)) (_hσ : ConjClasses.mk σ = C)
    (𝔭 : Ideal (𝓞 K)) [𝔭.IsPrime] (hunr : UnramifiedIn K L 𝔭)
    (_hCfrob : frobeniusClass K L 𝔭 = C) :
    Nat.card {𝔓 : Ideal (𝓞 L) // ∃ (_ : 𝔓.IsPrime) (hP : 𝔓.LiesOver 𝔭)
        (_ : 𝔓 ≠ ⊥),
        frobeniusAt K L 𝔓
            (by rw [show 𝔓.under (𝓞 K) = 𝔭 from hP.over.symm]; exact hunr 𝔓 hP)
          = σ}
      * orderOf σ * Nat.card C.carrier
      = Nat.card Gal(L/K) := by
  rw [mul_right_comm,
    count_frobenius_eq_sigma_mul_card_carrier K L σ C _hσ 𝔭 hunr _hCfrob]
  exact card_primesAbove_mul_orderOf_eq K L σ C _hσ 𝔭 hunr _hCfrob

/-- **Density-lift through the fixed-field subextension** (Sharifi 7.2.2
Step 1, p. 143). Let `σ ∈ Gal(L/K)`, `E = L^⟨σ⟩` the fixed field of the
cyclic subgroup `⟨σ⟩`, and `σ_E ∈ Gal(L/E)` the corresponding element.
Given the abelian-case density over `E` for the Frobenius-fibre of `σ_E`
(value `1/|Gal(L/E)|`), the density over `K` of the Frobenius **class** of
`σ` is `|C|/|G|`.

Source quote (verbatim, p. 143): "δ(S) = … = (f|C|/|G|) δ(T_σ),
recalling once again that `Σ_𝔭 N𝔭^{-s} ~ Σ_P NP^{-s}`. Supposing the
theorem for K/E, we have δ(T_σ) = 1/f, and we therefore obtain δ(S) =
|C|/|G|." Here `f = ord σ = |Gal(L/E)|`, and the counting factor is
`count_primes_above_with_frobenius_eq_sigma`.

The hypothesis `hEfix` records that `E` is the fixed field of `⟨σ⟩`; the
hypothesis `hab` is the abelian-case output for `L/E` from
`chebotarev_abelian`. -/
theorem density_lift_through_fixedField
    [FiniteDimensional K L] (σ : Gal(L/K)) (E : IntermediateField K L) (σE : Gal(L/E))
    (_hEfix : E = IntermediateField.fixedField (Subgroup.zpowers σ))
    (_hab : HasDirichletDensity ↥E
        {P : Ideal (𝓞 ↥E) | P.IsPrime ∧ UnramifiedIn ↥E L P ∧
          frobeniusClass ↥E L P = ConjClasses.mk σE}
        ((Nat.card Gal(L/E) : ℝ)⁻¹)) :
    HasDirichletDensity K
      {𝔭 : Ideal (𝓞 K) | 𝔭.IsPrime ∧ UnramifiedIn K L 𝔭 ∧
        frobeniusClass K L 𝔭 = ConjClasses.mk σ}
      ((Nat.card (ConjClasses.mk σ).carrier : ℝ) / Nat.card Gal(L/K)) := by
  sorry

/-- **Chebotarev's density theorem** (Sharifi 7.2.2; SL Appendix).

For a finite Galois extension `L/K` of number fields with Galois group `G`
and a conjugacy class `C ⊆ G`, the Dirichlet density of the set of primes
`𝔭` of `𝓞 K` (unramified in `L`) such that the Frobenius conjugacy class of
`𝔭` is `C` equals `|C| / |G|`. -/
theorem chebotarev_density
    [FiniteDimensional K L] (C : ConjClasses Gal(L/K)) :
    HasDirichletDensity K
      {𝔭 : Ideal (𝓞 K) | 𝔭.IsPrime ∧ UnramifiedIn K L 𝔭 ∧
        frobeniusClass K L 𝔭 = C}
      ((Nat.card C.carrier : ℝ) / Nat.card Gal(L/K)) := by
  obtain ⟨σ, rfl⟩ := ConjClasses.mk_surjective C
  have e := IntermediateField.subgroupEquivAlgEquiv (Subgroup.zpowers σ)
  have : IsMulCommutative Gal(L/(IntermediateField.fixedField (Subgroup.zpowers σ))) :=
    .of_comm fun a b => by
      obtain ⟨x, rfl⟩ := e.surjective a
      obtain ⟨y, rfl⟩ := e.surjective b
      rw [← map_mul e x y, ← map_mul e y x, mul_comm' x y]
  exact density_lift_through_fixedField K L σ
    (IntermediateField.fixedField (Subgroup.zpowers σ))
    (e ⟨σ, Subgroup.mem_zpowers σ⟩) rfl
    (chebotarev_abelian _ L (e ⟨σ, Subgroup.mem_zpowers σ⟩))

/-- In a commutative finite group every conjugacy class is a singleton,
so `|C| = 1`. -/
theorem ConjClasses_carrier_card_eq_one_of_comm
    {G : Type*} [Group G] [IsMulCommutative G] [Finite G] (g : G) :
    Nat.card (ConjClasses.mk g).carrier = 1 := by
  letI : CommMonoid G := IsMulCommutative.instCommMonoid
  have h : (ConjClasses.mk g).carrier = {g} := by
    ext a
    simp [ConjClasses.mem_carrier_iff_mk_eq, ConjClasses.mk_eq_mk_iff_isConj, isConj_iff_eq]
  rw [h, Nat.card_coe_set_eq, Set.ncard_singleton]

/-- **Chebotarev's density theorem, abelian case.** For an abelian Galois
extension `L/K`, the Dirichlet density of primes `𝔭` of `𝓞 K` unramified in
`L` whose Frobenius conjugacy class is `C` is `|C| / |Gal(L/K)|`. -/
theorem chebotarev_density_of_comm
    [FiniteDimensional K L] [IsMulCommutative Gal(L/K)] (C : ConjClasses Gal(L/K)) :
    HasDirichletDensity K
      {𝔭 : Ideal (𝓞 K) | 𝔭.IsPrime ∧ UnramifiedIn K L 𝔭 ∧
        frobeniusClass K L 𝔭 = C}
      ((Nat.card C.carrier : ℝ) / Nat.card Gal(L/K)) := by
  obtain ⟨σ, rfl⟩ := ConjClasses.mk_surjective C
  simpa [ConjClasses_carrier_card_eq_one_of_comm σ] using chebotarev_abelian K L σ

/-- Sub-lemma: a set of prime ideals with positive Dirichlet density is
infinite. Contrapositive: a finite set has density `0` (by
`hasDirichletDensity_of_finite` from `Density.lean`). -/
theorem infinite_of_hasDirichletDensity_pos
    {S : Set (Ideal (𝓞 K))} {δ : ℝ} (h : HasDirichletDensity K S δ) (hδ : 0 < δ) :
    S.Infinite :=
  fun hfin ↦ hδ.ne' (tendsto_nhds_unique h (hasDirichletDensity_of_finite K hfin))

/-- The carrier of a conjugacy class in a finite group has positive cardinality. -/
theorem ConjClasses_carrier_card_pos
    {G : Type*} [Group G] [Finite G] (C : ConjClasses G) :
    0 < Nat.card C.carrier := by
  obtain ⟨a, rfl⟩ := ConjClasses.mk_surjective C
  have : Nonempty (ConjClasses.mk a).carrier := ⟨⟨a, ConjClasses.mem_carrier_mk⟩⟩
  exact Nat.card_pos

/-- Existence of *infinitely many* primes with each Frobenius conjugacy class
— a qualitative corollary of `chebotarev_density`. -/
theorem infinite_setOf_frobenius_class
    [FiniteDimensional K L] (C : ConjClasses Gal(L/K)) :
    Set.Infinite
      {𝔭 : Ideal (𝓞 K) | 𝔭.IsPrime ∧ UnramifiedIn K L 𝔭 ∧
        frobeniusClass K L 𝔭 = C} := by
  refine infinite_of_hasDirichletDensity_pos K (chebotarev_density K L C) ?_
  apply div_pos
  · exact_mod_cast ConjClasses_carrier_card_pos C
  · exact_mod_cast Nat.card_pos (α := Gal(L/K))

/-- The identity conjugacy class in a finite group has carrier of cardinality `1`. -/
theorem ConjClasses_mk_one_carrier_card_eq_one
    (G : Type*) [Group G] [Finite G] :
    Nat.card (ConjClasses.mk (1 : G)).carrier = 1 := by
  have h : (ConjClasses.mk (1 : G)).carrier = {1} := by
    simp [Set.ext_iff, ConjClasses.mem_carrier_iff_mk_eq, ConjClasses.mk_eq_mk_iff_isConj]
  rw [h, Nat.card_coe_set_eq, Set.ncard_singleton]

/-- **Density of completely split primes** (Sharifi 7.1.14, as a corollary of
Chebotarev applied to the identity conjugacy class).

The Dirichlet density of primes `𝔭` of `𝓞 K` that split completely in `L`
equals `1 / [L : K]`. -/
theorem density_split_completely :
    HasDirichletDensity K
      {𝔭 : Ideal (𝓞 K) | 𝔭.IsPrime ∧ UnramifiedIn K L 𝔭 ∧
        frobeniusClass K L 𝔭 = ConjClasses.mk 1}
      ((Module.finrank K L : ℝ)⁻¹) := by
  have h := chebotarev_density K L (ConjClasses.mk (1 : Gal(L/K)))
  rw [ConjClasses_mk_one_carrier_card_eq_one Gal(L/K), IsGalois.card_aut_eq_finrank K L] at h
  simpa using h

/-- **Dirichlet's theorem on primes in arithmetic progressions**, as a
density refinement of `Nat.infinite_setOf_prime_and_eq_mod`.

For coprime integers `a, n` with `1 ≤ n` and `gcd a n = 1`, the Dirichlet
density of primes `p` with `p ≡ a mod n` equals `1 / φ(n)`. This is the
specialisation of Chebotarev to `K = ℚ`, `L = ℚ(μ_n)` (Sharifi 7.2.3). -/
theorem dirichlet_primes_in_AP (n : ℕ) (hn : 1 ≤ n) (a : ZMod n) (ha : IsUnit a) :
    HasDirichletDensity ℚ
      ((fun p : ℕ ↦ Ideal.span {(p : 𝓞 ℚ)}) ''
        {p : ℕ | p.Prime ∧ (p : ZMod n) = a})
      ((Nat.totient n : ℝ)⁻¹) := by
  sorry

end Chebotarev
