import Verso
import VersoManual
import VersoBlueprint
import CebotarevDensity

open Verso.Genre
open Verso.Genre.Manual
open Informal

tex_prelude r#"\def\Z{\mathbb{Z}}\def\Q{\mathbb{Q}}\def\R{\mathbb{R}}\def\C{\mathbb{C}}\def\N{\mathbb{N}}\def\F{\mathbb{F}}\def\OK{\mathcal{O}_K}\def\Ocirc{\mathcal{O}}\def\Gal#1{\mathrm{Gal}(#1)}\def\Norm#1{\mathrm{N}(#1)}\def\fp{\mathfrak{p}}\def\fP{\mathfrak{P}}\def\Frob{\mathrm{Frob}}\def\Re{\operatorname{Re}}\def\re{\operatorname{Re}}\def\set#1{\left\{#1\right\}}\def\setof#1#2{\left\{#1\;\middle|\;#2\right\}}\def\abs#1{\left\lvert#1\right\rvert}\def\norm#1{\left\lVert#1\right\rVert}\def\ang#1{\left\langle#1\right\rangle}"#

#doc (Manual) "Chebotarev density theorem" =>

The general Galois case is reduced to the abelian case via the cyclic
subextension generated by a class representative. Source: Sharifi 7.2.2
Step~1 (p.~143).

:::lemma_ "count-primes-above-frob-sigma" (lean := "Chebotarev.count_primes_above_with_frobenius_eq_sigma")

Let $`L/K` be a finite Galois extension with $`G=\Gal{L/K}`,
$`C\subseteq G` a conjugacy class, $`\sigma\in C`, and $`\fp` a nonzero
prime of $`\OK` unramified in $`L` with $`\sigma_\fp = C`. The number
of primes $`\fP` of $`\Ocirc_L` above $`\fp` with $`\Frob_\fP = \sigma`
is exactly $`\abs{G}/(f\cdot\abs{C})`, where $`f = \mathrm{ord}(\sigma)`.

{uses "frobenius-at"}[]
{uses "frobenius-class"}[]
:::

:::proof "count-primes-above-frob-sigma"

The Galois group $`G` acts transitively on primes above $`\fp`, with
stabiliser $`D_\fP`. Hence the orbit has size $`\abs{G}/\abs{D_\fP}`. For
unramified $`\fp`, $`D_\fP=\ang{\Frob_\fP}` has order $`f`, so there are
$`\abs{G}/f` primes above $`\fp`. Their Frobenius elements form a
$`G`-orbit in $`C` (under conjugation), which is all of $`C` by
transitivity; this orbit has size $`\abs{C}`, and within each orbit
the count of representatives $`\sigma` is $`\abs{G}/(f\cdot\abs{C})`
(Sharifi p.~143).

:::

:::lemma_ "density-lift-fixedfield" (lean := "Chebotarev.density_lift_through_fixedField")

*Density lift through the fixed field.*
Let $`\sigma\in\Gal{L/K}`, $`E = L^{\ang\sigma}`, and $`\sigma_E\in\Gal{L/E}`
the corresponding element. Given the abelian-case density over $`E` for
the Frobenius-fibre of $`\sigma_E` (value $`1/\abs{\Gal{L/E}}`), the
$`K`-density of the Frobenius class $`[\sigma]` is $`\abs{[\sigma]}/\abs{G}`.

{uses "dirichlet-density"}[]
{uses "frobenius-class"}[]
{uses "count-primes-above-frob-sigma"}[]
{uses "prime-ideal-sum-log"}[]
:::

:::proof "density-lift-fixedfield"

For primes $`P` of $`E` above $`\fp\in S = \setof{\fp}{\sigma_\fp = [\sigma]}`,
exactly $`\abs{G}/(f\abs{C})` of the primes of $`L` above have Frobenius
$`\sigma` ({bpref "count-primes-above-frob-sigma"}[]); with $`\sum_\fp
N\fp^{-s} \sim \sum_P NP^{-s}` ({bpref "prime-ideal-sum-log"}[] over both
$`K` and $`E`), $`\delta_K(S) = (f\abs{C}/\abs{G})\,\delta_E(T_\sigma) =
(f\abs{C}/\abs{G})(1/f) = \abs{C}/\abs{G}`.

:::

:::theorem "chebotarev-density" (lean := "Chebotarev.chebotarev_density")

*Chebotarev density theorem.*
For a finite Galois extension $`L/K` of number fields with
$`G=\Gal{L/K}` and any conjugacy class $`C\subseteq G`,
$$`
    \delta\bigl(\setof{\fp\subset\OK}{\sigma_\fp = C}\bigr)
    \;=\; \frac{\abs{C}}{\abs{G}}.
`

{uses "chebotarev-abelian"}[]
{uses "density-lift-fixedfield"}[]
:::

:::proof "chebotarev-density"

Pick a representative $`\sigma\in C` (`ConjClasses.mk_surjective`)
and let $`E = L^{\ang\sigma}` be the fixed field of $`\ang\sigma`. The map
$`\ang\sigma \xrightarrow{\sim} \Gal{L/E}`
(`IntermediateField.subgroupEquivAlgEquiv`) shows $`\Gal{L/E}` is
commutative (as $`\ang\sigma` is cyclic), so $`L/E` is abelian and
{bpref "chebotarev-abelian"}[] applies to its Frobenius $`\sigma_E`, giving
$`\delta_E(T_\sigma) = 1/\abs{\Gal{L/E}}`. Feeding this into the density
lift {bpref "density-lift-fixedfield"}[] yields $`\abs{C}/\abs{G}`.

:::

:::theorem "chebotarev-density-comm" (lean := "Chebotarev.chebotarev_density_of_comm")

*Chebotarev, abelian case.*
When $`G = \Gal{L/K}` is abelian, the Chebotarev density theorem holds:
for every conjugacy class $`C`,
$`\delta(\setof{\fp}{\sigma_\fp = C}) = \abs{C}/\abs{G}`.

{uses "chebotarev-abelian"}[]
{uses "conjclasses-carrier-card-one-comm"}[]
:::

:::proof "chebotarev-density-comm"

In an abelian group each class $`C = [\sigma]` is a singleton
({bpref "conjclasses-carrier-card-one-comm"}[]), so $`\abs{C} = 1` and
the target density is $`1/\abs{G}`; this is exactly
{bpref "chebotarev-abelian"}[] for the representative $`\sigma`.

:::

# Corollaries

The corollaries below are derived directly by composition from
{bpref "chebotarev-density"}[]. The Lean derivations use four small
helper sub-lemmas captured here.

:::lemma_ "conjclasses-mk-one-carrier-card-one" (lean := "Chebotarev.ConjClasses_mk_one_carrier_card_eq_one")

Let $`G` be a finite group. The conjugacy class of the identity has
cardinality $`1`:
$`\abs{(\mathrm{Conj}(G))_{\{1\}}} = 1`.

:::

:::proof "conjclasses-mk-one-carrier-card-one"

The carrier is $`\{1\}` (by `isConj_one_left`, $`a` conjugate to
$`1` iff $`a = 1`); a singleton has cardinality $`1`.

:::

:::lemma_ "conjclasses-carrier-card-one-comm" (lean := "Chebotarev.ConjClasses_carrier_card_eq_one_of_comm")

In a commutative finite group, every conjugacy class is a singleton,
so has cardinality $`1`.

:::

:::proof "conjclasses-carrier-card-one-comm"

By `isConj_iff_eq` (conjugacy is equality in a commutative
monoid), the carrier of $`[g]` is $`\{g\}`.

:::

:::lemma_ "infinite-of-density-pos" (lean := "Chebotarev.infinite_of_hasDirichletDensity_pos")

A set $`S` of prime ideals with positive Dirichlet density is infinite.

:::

:::proof "infinite-of-density-pos"

Contrapositive: a finite set of primes has density $`0` by
{bpref "has-density-finite"}[] (the finite case of
{bpref "dirichlet-density"}[]).

:::

:::lemma_ "conjclasses-carrier-card-pos" (lean := "Chebotarev.ConjClasses_carrier_card_pos")

Every conjugacy class in a finite group has cardinality at least $`1`
(it contains at least its own representative).

:::

:::proof "conjclasses-carrier-card-pos"

A representative $`a` with $`[a] = C` lies in the carrier
(`ConjClasses.mk_surjective` + `mem_carrier_iff_mk_eq`),
so the carrier is nonempty; a nonempty finite set has positive
cardinality.

:::

:::corollary "density-split-completely" (lean := "Chebotarev.density_split_completely")

For a finite Galois extension $`L/K` of number fields, the Dirichlet
density of primes of $`\OK` that split completely in $`L` equals
$`1/[L:K]`.

{uses "chebotarev-density"}[]
{uses "conjclasses-mk-one-carrier-card-one"}[]
:::

:::proof "density-split-completely"

A prime $`\fp` splits completely in $`L` iff every $`\fP \mid \fp` has
$`\Frob_\fP = 1`, i.e. the Frobenius conjugacy class is the trivial
class. Apply {bpref "chebotarev-density"}[] at $`C = \mathrm{Conj}(G)_{\{1\}}`;
by {bpref "conjclasses-mk-one-carrier-card-one"}[] the numerator
$`\abs{C} = 1` and by mathlib's `IsGalois.card_aut_eq_finrank`
the denominator $`\abs{\Gal{L/K}} = [L:K]`, so the density equals
$`1/[L:K]`.

:::

:::corollary "infinite-frobenius-class" (lean := "Chebotarev.infinite_setOf_frobenius_class")

For a finite Galois extension $`L/K` of number fields and any conjugacy
class $`C \subseteq \Gal{L/K}`, the set of primes $`\fp` of $`\OK`
unramified in $`L` with Frobenius conjugacy class $`C` is infinite.

{uses "chebotarev-density"}[]
{uses "infinite-of-density-pos"}[]
{uses "conjclasses-carrier-card-pos"}[]
:::

:::proof "infinite-frobenius-class"

{bpref "chebotarev-density"}[] gives Dirichlet density
$`\abs{C}/\abs{G}`, which is positive since $`\abs{C} \ge 1`
({bpref "conjclasses-carrier-card-pos"}[]) and $`\abs{G} \ge 1`. Apply
{bpref "infinite-of-density-pos"}[].

:::

:::corollary "dirichlet-ap-density" (lean := "Chebotarev.dirichlet_primes_in_AP")

*Dirichlet, density form.*
For $`n \ge 1` and $`a \in (\Z/n\Z)^\times`, the Dirichlet density of
the rational primes $`p` with $`p \equiv a \pmod{n}` equals
$`1/\varphi(n)`.

{uses "chebotarev-density"}[]
:::

:::proof "dirichlet-ap-density"

Specialise {bpref "chebotarev-density"}[] to $`K = \Q`, $`L = \Q(\zeta_n)`.
The cyclotomic character identifies $`\Gal{\Q(\zeta_n)/\Q}` with
$`(\Z/n\Z)^\times`; under this identification, the Frobenius
$`\sigma_p` at unramified $`p` corresponds to $`p \bmod n`. The Galois
group is abelian, so each conjugacy class is a singleton; the set of
primes with $`p \equiv a \pmod{n}` is the Frobenius preimage of
$`\{a\}`, whose density is $`1/\varphi(n)`.

:::
